# Generated by Django 4.1.4 on 2022-12-21 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youTube', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('profile_pic', models.ImageField(null=True, upload_to='youTube/images/channels')),
                ('banner', models.ImageField(null=True, upload_to='youTube/images/banners')),
                ('subs', models.IntegerField(default=0)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('users', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('desc', models.TextField(default='')),
                ('cover_img', models.ImageField(upload_to='youTube/images/vidoes_img')),
                ('vid_url', models.ImageField(upload_to='youTube/images/vidoes_vid')),
                ('like', models.IntegerField(default=0)),
                ('dis_like', models.IntegerField(default=0)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('channels', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='youTube.channel')),
            ],
        ),
    ]
