# Generated by Django 4.1.4 on 2022-12-21 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youTube', '0002_channel_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='cover_img',
            field=models.ImageField(null=True, upload_to='youTube/images/vidoes_img'),
        ),
        migrations.AlterField(
            model_name='video',
            name='vid_url',
            field=models.ImageField(null=True, upload_to='youTube/images/vidoes_vid'),
        ),
    ]
