# Generated by Django 4.1.4 on 2022-12-25 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youTube', '0005_alter_video_vid_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
